// A curated list of well-known Qatar areas/districts, used to suggest
// locations even before any listing has been posted there yet. Real listing
// data (from the database) is merged on top of this at query time, so an
// area actually in use always shows up too, even if it's not in this list.
export const QATAR_AREAS: string[] = [
  // Doha
  "Doha",
  "West Bay",
  "West Bay Lagoon",
  "Onaiza",
  "Al Dafna",
  "Diplomatic Area",
  "Old Airport",
  "Msheireb",
  "Souq Waqif",
  "Al Bidda",
  "Fereej Bin Mahmoud",
  "Fereej Bin Mahmoud North",
  "Fereej Abdul Aziz",
  "Al Sadd",
  "Al Mirqab",
  "Bin Omran",
  "Al Nasr",
  "Najma",
  "Nuaija",
  "Old Salata",
  "New Salata",
  "Al Souq",
  "Umm Ghuwailina",
  "Al Rufaa",
  "Al Ghanim",
  "Al Mansoura",
  "Al Asmakh",
  "Corniche",
  "Al Waab",
  "Aspire Zone",
  "Al Thumama",
  "Al Gharrafa",
  "Gharrafat Al Rayyan",
  "Muaither",
  "Ain Khaled",
  "Abu Hamour",
  "Al Maamoura",
  "Al Messila",
  "Al Markhiya",
  "Umm Lekhba",
  "Al Duhail",
  "Madinat Khalifa",
  "Rawdat Al Khail",
  "Al Hilal",
  "Al Sailiya",
  "Izghawa",
  "Wadi Al Banat",
  "Al Kheesa",
  "Al Kharaitiyat",
  "Umm Salal Mohammed",
  "Umm Salal Ali",
  // Lusail & The Pearl
  "Lusail",
  "Fox Hills",
  "Marina District",
  "Al Erkyah",
  "Al Qutaifiya",
  "The Pearl-Qatar",
  "Porto Arabia",
  "Viva Bahriya",
  "Qanat Quartier",
  "Giardino Village",
  // Al Rayyan
  "Al Rayyan",
  "Al Rayyan Al Jadeed",
  "Bu Hamour",
  "Al Shahaniya",
  "Dukhan",
  "Zekreet",
  // Al Wakrah / Mesaieed
  "Al Wakrah",
  "Al Wukair",
  "Mesaieed",
  // Al Khor
  "Al Khor",
  "Al Thakhira",
  "Ras Laffan",
  "Simaisma",
  // Al Daayen
  "Al Daayen",
  "Leabaib",
  "Umm Qarn",
  // Al Shamal
  "Madinat ash Shamal",
  "Al Ruwais",
  "Al Zubarah",
].sort((a, b) => a.localeCompare(b));
